_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.18.7
            "6": 4.49.0
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 8
block_size:
    value: 512
device:
    value: cuda
dropout:
    value: 0.1
learning_rate:
    value: 3e-05
max_iters:
    value: 1000
model:
    value: gpt2-finetuned
num_classes:
    value: 3
