_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 64
block_size:
    value: 512
device:
    value: cuda
dropout:
    value: 0.1
eval_interval:
    value: 500
eval_iters:
    value: 20
learning_rate:
    value: 0.0003
log_interval:
    value: 100
lr_decay_iters:
    value: 5000
max_iters:
    value: 5000
min_lr:
    value: 3e-05
model:
    value: scratch-char-level
n_embd:
    value: 384
n_head:
    value: 6
n_layer:
    value: 6
num_classes:
    value: 3
out_dir:
    value: out-sentiment-scratch
vocab_size:
    value: 40
warmup_iters:
    value: 100
